import type { Device } from './types'

// dummy data for devices
export const devices: Device[] = [
  {
    id: 'factory-001',
    name: 'Factory Sensor A',
    location: 'Assembly Line 1',
    status: 'online',
    battery: 78,
    temperature: 36.8,
    signalStrength: 'good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'factory-002',
    name: 'Factory Sensor B',
    location: 'Assembly Line 2',
    status: 'offline',
    battery: 0,
    temperature: 0,
    signalStrength: 'poor',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'factory-003',
    name: 'Motor Vibration Sensor',
    location: 'Press Machine 7',
    status: 'online',
    battery: 92,
    temperature: 42.5,
    signalStrength: 'moderate',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'factory-004',
    name: 'Boiler Pressure Sensor',
    location: 'Boiler Room',
    status: 'online',
    battery: 54,
    temperature: 75.2,
    signalStrength: 'good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'warehouse-001',
    name: 'Warehouse Temp Sensor',
    location: 'Cold Storage Zone',
    status: 'online',
    battery: 65,
    temperature: 12.4,
    signalStrength: 'good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'warehouse-002',
    name: 'Warehouse Conveyor',
    location: 'Loading Dock 3',
    status: 'online',
    battery: 69,
    temperature: 48.9,
    signalStrength: 'good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'warehouse-003',
    name: 'Humidity Sensor',
    location: 'Storage Aisle 12',
    status: 'error',
    battery: 34,
    temperature: 28.3,
    signalStrength: 'poor',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'warehouse-004',
    name: 'Air Quality Sensor',
    location: 'Packing Section',
    status: 'online',
    battery: 88,
    temperature: 24.1,
    signalStrength: 'good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'hq-001',
    name: 'HQ Office HVAC Sensor',
    location: 'Main Office',
    status: 'online',
    battery: 77,
    temperature: 23.5,
    signalStrength: 'excellent',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'hq-002',
    name: 'HQ Camera Sensor',
    location: 'Server Room',
    status: 'online',
    battery: 100,
    temperature: 29.8,
    signalStrength: 'excellent',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'solar-001',
    name: 'Solar Panel Sensor',
    location: 'Rooftop',
    status: 'online',
    battery: 55,
    temperature: 40.3,
    signalStrength: 'moderate',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'wind-001',
    name: 'Turbine Rotation Sensor',
    location: 'Windmill Zone B',
    status: 'online',
    battery: 61,
    temperature: 33.7,
    signalStrength: 'good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'wind-002',
    name: 'Wind Speed Sensor',
    location: 'Zone C Tower 3',
    status: 'offline',
    battery: 0,
    temperature: 0,
    signalStrength: 'poor',
    lastUpdated: new Date().toISOString(),
  },

  // 🌐 Remote Sites
  {
    id: 'remote-001',
    name: 'Remote Pump Sensor',
    location: 'Field Station 5',
    status: 'online',
    battery: 52,
    temperature: 39.9,
    signalStrength: 'moderate',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'remote-002',
    name: 'Soil Moisture Sensor',
    location: 'Irrigation Zone D',
    status: 'error',
    battery: 27,
    temperature: 30.5,
    signalStrength: 'poor',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'remote-003',
    name: 'Rainfall Detector',
    location: 'Weather Station 3',
    status: 'online',
    battery: 84,
    temperature: 25.2,
    signalStrength: 'good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'remote-004',
    name: 'River Water Level Sensor',
    location: 'Bridge Point 7',
    status: 'online',
    battery: 72,
    temperature: 22.1,
    signalStrength: 'excellent',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'remote-005',
    name: 'Battery Backup Node',
    location: 'Control Station 2',
    status: 'maintenance',
    battery: 64,
    temperature: 35.6,
    signalStrength: 'moderate',
    lastUpdated: new Date().toISOString(),
  },
]

// Export a function to get the data
export const getDevices = (): Device[] => devices

export const getDeviceById = (id: string): Device | undefined =>
  devices.find((d) => d.id === id)
