import type { Device } from './types'

// dummy data for devices
export const devices: Device[] = [
  {
    id: 'factory-001',
    name: 'Factory Sensor A',
    location: 'Assembly Line 1',
    status: 'online',
    battery: 78,
    temperature: 36.8,
    signalStrength: 'Good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'factory-002',
    name: 'Factory Sensor B',
    location: 'Assembly Line 2',
    status: 'offline',
    battery: 0,
    temperature: 0,
    signalStrength: 'Poor',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'factory-003',
    name: 'Motor Vibration Sensor',
    location: 'Press Machine 7',
    status: 'online',
    battery: 92,
    temperature: 42.5,
    signalStrength: 'Moderate',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'factory-004',
    name: 'Boiler Pressure Sensor',
    location: 'Boiler Room',
    status: 'online',
    battery: 54,
    temperature: 75.2,
    signalStrength: 'Good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'warehouse-001',
    name: 'Warehouse Temperature Sensor',
    location: 'Cold Storage Zone',
    status: 'online',
    battery: 65,
    temperature: 12.4,
    signalStrength: 'Good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'warehouse-002',
    name: 'Warehouse Conveyor',
    location: 'Loading Dock 3',
    status: 'online',
    battery: 69,
    temperature: 48.9,
    signalStrength: 'Good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'warehouse-003',
    name: 'Humidity Sensor',
    location: 'Storage Aisle 12',
    status: 'error',
    battery: 34,
    temperature: 28.3,
    signalStrength: 'Poor',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'warehouse-004',
    name: 'CO₂ Air Quality Sensor',
    location: 'Packing Section',
    status: 'online',
    battery: 88,
    temperature: 24.1,
    signalStrength: 'Good',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'hq-001',
    name: 'HQ Office HVAC Sensor',
    location: 'Main Office',
    status: 'online',
    battery: 77,
    temperature: 23.5,
    signalStrength: 'Excellent',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'hq-002',
    name: 'HQ Security Camera Sensor',
    location: 'Server Room',
    status: 'online',
    battery: 100,
    temperature: 29.8,
    signalStrength: 'Excellent',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'solar-001',
    name: 'Solar Panel Inverter Sensor',
    location: 'Rooftop',
    status: 'online',
    battery: 55,
    temperature: 40.3,
    signalStrength: 'Moderate',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'wind-001',
    name: 'Turbine Rotation Sensor',
    location: 'Windmill Zone B',
    status: 'online',
    battery: 61,
    temperature: 33.7,
    signalStrength: 'Good',
    lastUpdated: new Date().toISOString(),
  },
]

// Export a function to get the data
export const getDevices = (): Device[] => devices
